<?php
/**
 * Share.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\ShareModule\Entity\Base;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Zikula\Core\Doctrine\EntityAccess;
use MU\ShareModule\Traits\GeographicalTrait;
use MU\ShareModule\Traits\StandardFieldsTrait;
use MU\ShareModule\Validator\Constraints as ShareAssert;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the base entity class for location entities.
 * The following annotation marks it as a mapped superclass so subclasses
 * inherit orm properties.
 *
 * @ORM\MappedSuperclass
 */
abstract class AbstractLocationEntity extends EntityAccess
{
    /**
     * Hook geographical behaviour embedding latitude and longitude fields.
     */
    use GeographicalTrait;

    /**
     * Hook standard fields behaviour embedding createdBy, updatedBy, createdDate, updatedDate fields.
     */
    use StandardFieldsTrait;

    /**
     * @var string The tablename this object maps to
     */
    protected $_objectType = 'location';
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", unique=true)
     * @var integer $id
     */
    protected $id = 0;
    
    /**
     * the current workflow state
     * @ORM\Column(length=20)
     * @Assert\NotBlank()
     * @ShareAssert\ListEntry(entityName="location", propertyName="workflowState", multiple=false)
     * @var string $workflowState
     */
    protected $workflowState = 'initial';
    
    /**
     * @ORM\Column(length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="255")
     * @var string $title
     */
    protected $title = '';
    
    /**
     * @ORM\Column(length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="255")
     * @var string $street
     */
    protected $street = '';
    
    /**
     * @ORM\Column(length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="255")
     * @var string $numberOfStreet
     */
    protected $numberOfStreet = '';
    
    /**
     * @ORM\Column(length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="255")
     * @var string $zipCode
     */
    protected $zipCode = '';
    
    /**
     * @ORM\Column(length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="255")
     * @var string $city
     */
    protected $city = '';
    
    /**
     * @ORM\Column(type="boolean")
     * @Assert\NotNull()
     * @Assert\Type(type="bool")
     * @var boolean $private
     */
    protected $private = false;
    
    /**
     * @ORM\Column(type="boolean")
     * @Assert\NotNull()
     * @Assert\Type(type="bool")
     * @var boolean $forMap
     */
    protected $forMap = true;
    
    
    /**
     * Bidirectional - One locationOfCompany [location] is linked by one companyOfLocation [company] (INVERSE SIDE).
     *
     * @ORM\OneToOne(targetEntity="MU\ShareModule\Entity\CompanyEntity", inversedBy="locationOfCompany")
     * @ORM\JoinTable(name="mu_share_company")
     * @Assert\Type(type="MU\ShareModule\Entity\CompanyEntity")
     * @var \MU\ShareModule\Entity\CompanyEntity $companyOfLocation
     */
    protected $companyOfLocation;
    
    /**
     * Bidirectional - Many location [locations] are linked by one pool [pool] (OWNING SIDE).
     *
     * @ORM\ManyToOne(targetEntity="MU\ShareModule\Entity\PoolEntity", inversedBy="location")
     * @ORM\JoinTable(name="mu_share_pool")
     * @Assert\Type(type="MU\ShareModule\Entity\PoolEntity")
     * @var \MU\ShareModule\Entity\PoolEntity $pool
     */
    protected $pool;
    
    /**
     * Bidirectional - One locationOfOffer [location] has many offerOfLocation [offers] (INVERSE SIDE).
     *
     * @ORM\OneToMany(targetEntity="MU\ShareModule\Entity\OfferEntity", mappedBy="locationOfOffer")
     * @ORM\JoinTable(name="mu_share_locationofofferofferoflocation")
     * @var \MU\ShareModule\Entity\OfferEntity[] $offerOfLocation
     */
    protected $offerOfLocation = null;
    
    
    /**
     * LocationEntity constructor.
     *
     * Will not be called by Doctrine and can therefore be used
     * for own implementation purposes. It is also possible to add
     * arbitrary arguments as with every other class method.
     */
    public function __construct()
    {
        $this->offerOfLocation = new ArrayCollection();
    }
    
    /**
     * Returns the _object type.
     *
     * @return string
     */
    public function get_objectType()
    {
        return $this->_objectType;
    }
    
    /**
     * Sets the _object type.
     *
     * @param string $_objectType
     *
     * @return void
     */
    public function set_objectType($_objectType)
    {
        if ($this->_objectType != $_objectType) {
            $this->_objectType = $_objectType;
        }
    }
    
    
    /**
     * Returns the id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Sets the id.
     *
     * @param integer $id
     *
     * @return void
     */
    public function setId($id)
    {
        if (intval($this->id) !== intval($id)) {
            $this->id = intval($id);
        }
    }
    
    /**
     * Returns the workflow state.
     *
     * @return string
     */
    public function getWorkflowState()
    {
        return $this->workflowState;
    }
    
    /**
     * Sets the workflow state.
     *
     * @param string $workflowState
     *
     * @return void
     */
    public function setWorkflowState($workflowState)
    {
        if ($this->workflowState !== $workflowState) {
            $this->workflowState = isset($workflowState) ? $workflowState : '';
        }
    }
    
    /**
     * Returns the title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }
    
    /**
     * Sets the title.
     *
     * @param string $title
     *
     * @return void
     */
    public function setTitle($title)
    {
        if ($this->title !== $title) {
            $this->title = isset($title) ? $title : '';
        }
    }
    
    /**
     * Returns the street.
     *
     * @return string
     */
    public function getStreet()
    {
        return $this->street;
    }
    
    /**
     * Sets the street.
     *
     * @param string $street
     *
     * @return void
     */
    public function setStreet($street)
    {
        if ($this->street !== $street) {
            $this->street = isset($street) ? $street : '';
        }
    }
    
    /**
     * Returns the number of street.
     *
     * @return string
     */
    public function getNumberOfStreet()
    {
        return $this->numberOfStreet;
    }
    
    /**
     * Sets the number of street.
     *
     * @param string $numberOfStreet
     *
     * @return void
     */
    public function setNumberOfStreet($numberOfStreet)
    {
        if ($this->numberOfStreet !== $numberOfStreet) {
            $this->numberOfStreet = isset($numberOfStreet) ? $numberOfStreet : '';
        }
    }
    
    /**
     * Returns the zip code.
     *
     * @return string
     */
    public function getZipCode()
    {
        return $this->zipCode;
    }
    
    /**
     * Sets the zip code.
     *
     * @param string $zipCode
     *
     * @return void
     */
    public function setZipCode($zipCode)
    {
        if ($this->zipCode !== $zipCode) {
            $this->zipCode = isset($zipCode) ? $zipCode : '';
        }
    }
    
    /**
     * Returns the city.
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }
    
    /**
     * Sets the city.
     *
     * @param string $city
     *
     * @return void
     */
    public function setCity($city)
    {
        if ($this->city !== $city) {
            $this->city = isset($city) ? $city : '';
        }
    }
    
    /**
     * Returns the private.
     *
     * @return boolean
     */
    public function getPrivate()
    {
        return $this->private;
    }
    
    /**
     * Sets the private.
     *
     * @param boolean $private
     *
     * @return void
     */
    public function setPrivate($private)
    {
        if (boolval($this->private) !== boolval($private)) {
            $this->private = boolval($private);
        }
    }
    
    /**
     * Returns the for map.
     *
     * @return boolean
     */
    public function getForMap()
    {
        return $this->forMap;
    }
    
    /**
     * Sets the for map.
     *
     * @param boolean $forMap
     *
     * @return void
     */
    public function setForMap($forMap)
    {
        if (boolval($this->forMap) !== boolval($forMap)) {
            $this->forMap = boolval($forMap);
        }
    }
    
    
    /**
     * Returns the company of location.
     *
     * @return \MU\ShareModule\Entity\CompanyEntity
     */
    public function getCompanyOfLocation()
    {
        return $this->companyOfLocation;
    }
    
    /**
     * Sets the company of location.
     *
     * @param \MU\ShareModule\Entity\CompanyEntity $companyOfLocation
     *
     * @return void
     */
    public function setCompanyOfLocation($companyOfLocation = null)
    {
        $this->companyOfLocation = $companyOfLocation;
    }
    
    /**
     * Returns the pool.
     *
     * @return \MU\ShareModule\Entity\PoolEntity
     */
    public function getPool()
    {
        return $this->pool;
    }
    
    /**
     * Sets the pool.
     *
     * @param \MU\ShareModule\Entity\PoolEntity $pool
     *
     * @return void
     */
    public function setPool($pool = null)
    {
        $this->pool = $pool;
    }
    
    /**
     * Returns the offer of location.
     *
     * @return \MU\ShareModule\Entity\OfferEntity[]
     */
    public function getOfferOfLocation()
    {
        return $this->offerOfLocation;
    }
    
    /**
     * Sets the offer of location.
     *
     * @param \MU\ShareModule\Entity\OfferEntity[] $offerOfLocation
     *
     * @return void
     */
    public function setOfferOfLocation($offerOfLocation)
    {
        foreach ($this->offerOfLocation as $offerSingle) {
            $this->removeOfferOfLocation($offerSingle);
        }
        foreach ($offerOfLocation as $offerSingle) {
            $this->addOfferOfLocation($offerSingle);
        }
    }
    
    /**
     * Adds an instance of \MU\ShareModule\Entity\OfferEntity to the list of offer of location.
     *
     * @param \MU\ShareModule\Entity\OfferEntity $offer The instance to be added to the collection
     *
     * @return void
     */
    public function addOfferOfLocation(\MU\ShareModule\Entity\OfferEntity $offer)
    {
        $this->offerOfLocation->add($offer);
        $offer->setLocationOfOffer($this);
    }
    
    /**
     * Removes an instance of \MU\ShareModule\Entity\OfferEntity from the list of offer of location.
     *
     * @param \MU\ShareModule\Entity\OfferEntity $offer The instance to be removed from the collection
     *
     * @return void
     */
    public function removeOfferOfLocation(\MU\ShareModule\Entity\OfferEntity $offer)
    {
        $this->offerOfLocation->removeElement($offer);
        $offer->setLocationOfOffer(null);
    }
    
    
    
    /**
     * Creates url arguments array for easy creation of display urls.
     *
     * @return array The resulting arguments list
     */
    public function createUrlArgs()
    {
        return [
            'id' => $this->getId()
        ];
    }
    
    /**
     * Returns the primary key.
     *
     * @return integer The identifier
     */
    public function getKey()
    {
        return $this->getId();
    }
    
    /**
     * Determines whether this entity supports hook subscribers or not.
     *
     * @return boolean
     */
    public function supportsHookSubscribers()
    {
        return true;
    }
    
    /**
     * Return lower case name of multiple items needed for hook areas.
     *
     * @return string
     */
    public function getHookAreaPrefix()
    {
        return 'musharemodule.ui_hooks.locations';
    }
    
    /**
     * Returns an array of all related objects that need to be persisted after clone.
     * 
     * @param array $objects The objects are added to this array. Default: []
     * 
     * @return array of entity objects
     */
    public function getRelatedObjectsToPersist(&$objects = []) 
    {
        return [];
    }
    
    /**
     * ToString interceptor implementation.
     * This method is useful for debugging purposes.
     *
     * @return string The output string for this entity
     */
    public function __toString()
    {
        return 'Location ' . $this->getKey() . ': ' . $this->getTitle();
    }
    
    /**
     * Clone interceptor implementation.
     * This method is for example called by the reuse functionality.
     * Performs a quite simple shallow copy.
     *
     * See also:
     * (1) http://docs.doctrine-project.org/en/latest/cookbook/implementing-wakeup-or-clone.html
     * (2) http://www.php.net/manual/en/language.oop5.cloning.php
     * (3) http://stackoverflow.com/questions/185934/how-do-i-create-a-copy-of-an-object-in-php
     */
    public function __clone()
    {
        // if the entity has no identity do nothing, do NOT throw an exception
        if (!$this->id) {
            return;
        }
    
        // otherwise proceed
    
        // unset identifier
        $this->setId(0);
    
        // reset workflow
        $this->setWorkflowState('initial');
    
        $this->setCreatedBy(null);
        $this->setCreatedDate(null);
        $this->setUpdatedBy(null);
        $this->setUpdatedDate(null);
    
    }
}
