<?php
/**
 * Share.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\ShareModule\Entity;

use MU\ShareModule\Entity\Base\AbstractOfferCategoryEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing offer categories.
 *
 * This is the concrete category class for offer entities.
 * @ORM\Entity(repositoryClass="\MU\ShareModule\Entity\Repository\OfferCategoryRepository")
 * @ORM\Table(name="mu_share_offer_category",
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="cat_unq", columns={"registryId", "categoryId", "entityId"})
 *     }
 * )
 */
class OfferCategoryEntity extends BaseEntity
{
    // feel free to add your own methods here
}
