<?php
/**
 * Share.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\ShareModule\Base;

/**
 * Events definition base class.
 */
abstract class AbstractShareEvents
{
    /**
     * The musharemodule.location_post_load event is thrown when locations
     * are loaded from the database.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterLocationEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const LOCATION_POST_LOAD = 'musharemodule.location_post_load';
    
    /**
     * The musharemodule.location_pre_persist event is thrown before a new location
     * is created in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterLocationEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const LOCATION_PRE_PERSIST = 'musharemodule.location_pre_persist';
    
    /**
     * The musharemodule.location_post_persist event is thrown after a new location
     * has been created in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterLocationEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const LOCATION_POST_PERSIST = 'musharemodule.location_post_persist';
    
    /**
     * The musharemodule.location_pre_remove event is thrown before an existing location
     * is removed from the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterLocationEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const LOCATION_PRE_REMOVE = 'musharemodule.location_pre_remove';
    
    /**
     * The musharemodule.location_post_remove event is thrown after an existing location
     * has been removed from the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterLocationEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const LOCATION_POST_REMOVE = 'musharemodule.location_post_remove';
    
    /**
     * The musharemodule.location_pre_update event is thrown before an existing location
     * is updated in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterLocationEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const LOCATION_PRE_UPDATE = 'musharemodule.location_pre_update';
    
    /**
     * The musharemodule.location_post_update event is thrown after an existing new location
     * has been updated in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterLocationEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const LOCATION_POST_UPDATE = 'musharemodule.location_post_update';
    
    /**
     * The musharemodule.offer_post_load event is thrown when offers
     * are loaded from the database.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterOfferEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const OFFER_POST_LOAD = 'musharemodule.offer_post_load';
    
    /**
     * The musharemodule.offer_pre_persist event is thrown before a new offer
     * is created in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterOfferEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const OFFER_PRE_PERSIST = 'musharemodule.offer_pre_persist';
    
    /**
     * The musharemodule.offer_post_persist event is thrown after a new offer
     * has been created in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterOfferEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const OFFER_POST_PERSIST = 'musharemodule.offer_post_persist';
    
    /**
     * The musharemodule.offer_pre_remove event is thrown before an existing offer
     * is removed from the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterOfferEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const OFFER_PRE_REMOVE = 'musharemodule.offer_pre_remove';
    
    /**
     * The musharemodule.offer_post_remove event is thrown after an existing offer
     * has been removed from the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterOfferEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const OFFER_POST_REMOVE = 'musharemodule.offer_post_remove';
    
    /**
     * The musharemodule.offer_pre_update event is thrown before an existing offer
     * is updated in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterOfferEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const OFFER_PRE_UPDATE = 'musharemodule.offer_pre_update';
    
    /**
     * The musharemodule.offer_post_update event is thrown after an existing new offer
     * has been updated in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterOfferEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const OFFER_POST_UPDATE = 'musharemodule.offer_post_update';
    
    /**
     * The musharemodule.pool_post_load event is thrown when pools
     * are loaded from the database.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterPoolEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const POOL_POST_LOAD = 'musharemodule.pool_post_load';
    
    /**
     * The musharemodule.pool_pre_persist event is thrown before a new pool
     * is created in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterPoolEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const POOL_PRE_PERSIST = 'musharemodule.pool_pre_persist';
    
    /**
     * The musharemodule.pool_post_persist event is thrown after a new pool
     * has been created in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterPoolEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const POOL_POST_PERSIST = 'musharemodule.pool_post_persist';
    
    /**
     * The musharemodule.pool_pre_remove event is thrown before an existing pool
     * is removed from the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterPoolEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const POOL_PRE_REMOVE = 'musharemodule.pool_pre_remove';
    
    /**
     * The musharemodule.pool_post_remove event is thrown after an existing pool
     * has been removed from the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterPoolEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const POOL_POST_REMOVE = 'musharemodule.pool_post_remove';
    
    /**
     * The musharemodule.pool_pre_update event is thrown before an existing pool
     * is updated in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterPoolEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const POOL_PRE_UPDATE = 'musharemodule.pool_pre_update';
    
    /**
     * The musharemodule.pool_post_update event is thrown after an existing new pool
     * has been updated in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterPoolEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const POOL_POST_UPDATE = 'musharemodule.pool_post_update';
    
    /**
     * The musharemodule.message_post_load event is thrown when messages
     * are loaded from the database.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterMessageEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const MESSAGE_POST_LOAD = 'musharemodule.message_post_load';
    
    /**
     * The musharemodule.message_pre_persist event is thrown before a new message
     * is created in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterMessageEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const MESSAGE_PRE_PERSIST = 'musharemodule.message_pre_persist';
    
    /**
     * The musharemodule.message_post_persist event is thrown after a new message
     * has been created in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterMessageEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const MESSAGE_POST_PERSIST = 'musharemodule.message_post_persist';
    
    /**
     * The musharemodule.message_pre_remove event is thrown before an existing message
     * is removed from the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterMessageEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const MESSAGE_PRE_REMOVE = 'musharemodule.message_pre_remove';
    
    /**
     * The musharemodule.message_post_remove event is thrown after an existing message
     * has been removed from the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterMessageEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const MESSAGE_POST_REMOVE = 'musharemodule.message_post_remove';
    
    /**
     * The musharemodule.message_pre_update event is thrown before an existing message
     * is updated in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterMessageEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const MESSAGE_PRE_UPDATE = 'musharemodule.message_pre_update';
    
    /**
     * The musharemodule.message_post_update event is thrown after an existing new message
     * has been updated in the system.
     *
     * The event listener receives an
     * MU\ShareModule\Event\FilterMessageEvent instance.
     *
     * @see MU\ShareModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const MESSAGE_POST_UPDATE = 'musharemodule.message_post_update';
    
}
