<?php
/**
 * Share.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\ShareModule\Base;

use Doctrine\DBAL\Connection;
use RuntimeException;
use Zikula\Core\AbstractExtensionInstaller;
use Zikula\CategoriesModule\Entity\CategoryRegistryEntity;

/**
 * Installer base class.
 */
abstract class AbstractShareModuleInstaller extends AbstractExtensionInstaller
{
    /**
     * Install the MUShareModule application.
     *
     * @return boolean True on success, or false
     *
     * @throws RuntimeException Thrown if database tables can not be created or another error occurs
     */
    public function install()
    {
        $logger = $this->container->get('logger');
        $userName = $this->container->get('zikula_users_module.current_user')->get('uname');
    
        // create all tables from according entity definitions
        try {
            $this->schemaTool->create($this->listEntityClasses());
        } catch (\Exception $exception) {
            $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $exception->getMessage());
            $logger->error('{app}: Could not create the database tables during installation. Error details: {errorMessage}.', ['app' => 'MUShareModule', 'errorMessage' => $exception->getMessage()]);
    
            return false;
        }
    
        // set up all our vars with initial values
        $this->setVar('maxRadius', '5000');
        $this->setVar('maxLocations', '5');
        $this->setVar('locationEntriesPerPage', '10');
        $this->setVar('linkOwnLocationsOnAccountPage', true);
        $this->setVar('offerEntriesPerPage', '10');
        $this->setVar('linkOwnOffersOnAccountPage', true);
        $this->setVar('poolEntriesPerPage', '10');
        $this->setVar('linkOwnPoolsOnAccountPage', true);
        $this->setVar('messageEntriesPerPage', '10');
        $this->setVar('linkOwnMessagesOnAccountPage', true);
        $this->setVar('enabledFinderTypes', [ 'location' ,  'offer' ,  'pool' ,  'message' ]);
        $this->setVar('defaultLatitude', '0.00');
        $this->setVar('defaultLongitude', '0.00');
        $this->setVar('defaultZoomLevel', '5');
        $this->setVar('tileLayerUrl', 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png');
        $this->setVar('tileLayerAttribution', '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors');
        $this->setVar('enableLocationGeoLocation', false);
        $this->setVar('enableOfferGeoLocation', false);
    
        $categoryRegistryIdsPerEntity = [];
    
        // add default entry for category registry (property named Main)
        $categoryHelper = new \MU\ShareModule\Helper\CategoryHelper(
            $this->container->get('translator.default'),
            $this->container->get('request_stack'),
            $logger,
            $this->container->get('zikula_users_module.current_user'),
            $this->container->get('zikula_categories_module.category_registry_repository'),
            $this->container->get('zikula_categories_module.api.category_permission')
        );
        $categoryGlobal = $this->container->get('zikula_categories_module.category_repository')->findOneBy(['name' => 'Global']);
        $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
    
        $registry = new CategoryRegistryEntity();
        $registry->setModname('MUShareModule');
        $registry->setEntityname('OfferEntity');
        $registry->setProperty($categoryHelper->getPrimaryProperty('Offer'));
        $registry->setCategory($categoryGlobal);
    
        try {
            $entityManager->persist($registry);
            $entityManager->flush();
        } catch (\Exception $exception) {
            $this->addFlash('error', $this->__f('Error! Could not create a category registry for the %entity% entity.', ['%entity%' => 'offer']));
            $logger->error('{app}: User {user} could not create a category registry for {entities} during installation. Error details: {errorMessage}.', ['app' => 'MUShareModule', 'user' => $userName, 'entities' => 'offers', 'errorMessage' => $exception->getMessage()]);
        }
        $categoryRegistryIdsPerEntity['offer'] = $registry->getId();
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the MUShareModule application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables can not be updated
     */
    public function upgrade($oldVersion)
    {
    /*
        $logger = $this->container->get('logger');
    
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case '1.0.0':
                // do something
                // ...
                // update the database schema
                try {
                    $this->schemaTool->update($this->listEntityClasses());
                } catch (\Exception $exception) {
                    $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $exception->getMessage());
                    $logger->error('{app}: Could not update the database tables during the upgrade. Error details: {errorMessage}.', ['app' => 'MUShareModule', 'errorMessage' => $exception->getMessage()]);
    
                    return false;
                }
        }
    
        // Note there are several helpers available for making migrating your extension from Zikula 1.3 to 1.4 easier.
        // The following convenience methods are each responsible for a single aspect of upgrading to Zikula 1.4.x.
    
        // here is a possible usage example
        // of course 1.2.3 should match the number you used for the last stable 1.3.x module version.
        /* if ($oldVersion = '1.2.3') {
            // rename module for all modvars
            $this->updateModVarsTo14();
            
            // update extension information about this app
            $this->updateExtensionInfoFor14();
            
            // rename existing permission rules
            $this->renamePermissionsFor14();
            
            // rename existing category registries
            $this->renameCategoryRegistriesFor14();
            
            // rename all tables
            $this->renameTablesFor14();
            
            // remove event handler definitions from database
            $this->dropEventHandlersFromDatabase();
            
            // update module name in the hook tables
            $this->updateHookNamesFor14();
            
            // update module name in the workflows table
            $this->updateWorkflowsFor14();
        } * /
    
        // remove obsolete persisted hooks from the database
        //$this->hookApi->uninstallSubscriberHooks($this->bundle->getMetaData());
    */
    
        // update successful
        return true;
    }
    
    /**
     * Renames the module name for variables in the module_vars table.
     */
    protected function updateModVarsTo14()
    {
        $conn = $this->getConnection();
        $conn->update('module_vars', ['modname' => 'MUShareModule'], ['modname' => 'Share']);
    }
    
    /**
     * Renames this application in the core's extensions table.
     */
    protected function updateExtensionInfoFor14()
    {
        $conn = $this->getConnection();
        $conn->update('modules', ['name' => 'MUShareModule', 'directory' => 'MU/ShareModule'], ['name' => 'Share']);
    }
    
    /**
     * Renames all permission rules stored for this app.
     */
    protected function renamePermissionsFor14()
    {
        $conn = $this->getConnection();
        $componentLength = strlen('Share') + 1;
    
        $conn->executeQuery("
            UPDATE group_perms
            SET component = CONCAT('MUShareModule', SUBSTRING(component, $componentLength))
            WHERE component LIKE 'Share%';
        ");
    }
    
    /**
     * Renames all category registries stored for this app.
     */
    protected function renameCategoryRegistriesFor14()
    {
        $conn = $this->getConnection();
        $componentLength = strlen('Share') + 1;
    
        $conn->executeQuery("
            UPDATE categories_registry
            SET modname = CONCAT('MUShareModule', SUBSTRING(modname, $componentLength))
            WHERE modname LIKE 'Share%';
        ");
    }
    
    /**
     * Renames all (existing) tables of this app.
     */
    protected function renameTablesFor14()
    {
        $conn = $this->getConnection();
    
        $oldPrefix = 'share_';
        $oldPrefixLength = strlen($oldPrefix);
        $newPrefix = 'mu_share_';
    
        $sm = $conn->getSchemaManager();
        $tables = $sm->listTables();
        foreach ($tables as $table) {
            $tableName = $table->getName();
            if (substr($tableName, 0, $oldPrefixLength) != $oldPrefix) {
                continue;
            }
    
            $newTableName = str_replace($oldPrefix, $newPrefix, $tableName);
    
            $conn->executeQuery("
                RENAME TABLE $tableName
                TO $newTableName;
            ");
        }
    }
    
    /**
     * Removes event handlers from database as they are now described by service definitions and managed by dependency injection.
     */
    protected function dropEventHandlersFromDatabase()
    {
        \EventUtil::unregisterPersistentModuleHandlers('Share');
    }
    
    /**
     * Updates the module name in the hook tables.
     */
    protected function updateHookNamesFor14()
    {
        $conn = $this->getConnection();
    
        $conn->update('hook_area', ['owner' => 'MUShareModule'], ['owner' => 'Share']);
    
        $componentLength = strlen('subscriber.share') + 1;
        $conn->executeQuery("
            UPDATE hook_area
            SET areaname = CONCAT('subscriber.musharemodule', SUBSTRING(areaname, $componentLength))
            WHERE areaname LIKE 'subscriber.share%';
        ");
    
        $conn->update('hook_binding', ['sowner' => 'MUShareModule'], ['sowner' => 'Share']);
    
        $conn->update('hook_runtime', ['sowner' => 'MUShareModule'], ['sowner' => 'Share']);
    
        $componentLength = strlen('share') + 1;
        $conn->executeQuery("
            UPDATE hook_runtime
            SET eventname = CONCAT('musharemodule', SUBSTRING(eventname, $componentLength))
            WHERE eventname LIKE 'share%';
        ");
    
        $conn->update('hook_subscriber', ['owner' => 'MUShareModule'], ['owner' => 'Share']);
    
        $componentLength = strlen('share') + 1;
        $conn->executeQuery("
            UPDATE hook_subscriber
            SET eventname = CONCAT('musharemodule', SUBSTRING(eventname, $componentLength))
            WHERE eventname LIKE 'share%';
        ");
    }
    
    /**
     * Updates the module name in the workflows table.
     */
    protected function updateWorkflowsFor14()
    {
        $conn = $this->getConnection();
        $conn->update('workflows', ['module' => 'MUShareModule'], ['module' => 'Share']);
        $conn->update('workflows', ['obj_table' => 'LocationEntity'], ['module' => 'MUShareModule', 'obj_table' => 'location']);
        $conn->update('workflows', ['obj_table' => 'OfferEntity'], ['module' => 'MUShareModule', 'obj_table' => 'offer']);
        $conn->update('workflows', ['obj_table' => 'PoolEntity'], ['module' => 'MUShareModule', 'obj_table' => 'pool']);
        $conn->update('workflows', ['obj_table' => 'MessageEntity'], ['module' => 'MUShareModule', 'obj_table' => 'message']);
    }
    
    /**
     * Returns connection to the database.
     *
     * @return Connection the current connection
     */
    protected function getConnection()
    {
        $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
    
        return $entityManager->getConnection();
    }
    
    /**
     * Uninstall MUShareModule.
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables or stored workflows can not be removed
     */
    public function uninstall()
    {
        $logger = $this->container->get('logger');
    
        try {
            $this->schemaTool->drop($this->listEntityClasses());
        } catch (\Exception $exception) {
            $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $exception->getMessage());
            $logger->error('{app}: Could not remove the database tables during uninstallation. Error details: {errorMessage}.', ['app' => 'MUShareModule', 'errorMessage' => $exception->getMessage()]);
    
            return false;
        }
    
        // remove all module vars
        $this->delVars();
    
        // remove category registry entries
        $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
        $registries = $this->container->get('zikula_categories_module.category_registry_repository')->findBy(['modname' => 'MUShareModule']);
        foreach ($registries as $registry) {
            $entityManager->remove($registry);
        }
        $entityManager->flush();
    
        // uninstallation successful
        return true;
    }
    
    /**
     * Build array with all entity classes for MUShareModule.
     *
     * @return array list of class names
     */
    protected function listEntityClasses()
    {
        $classNames = [];
        $classNames[] = 'MU\ShareModule\Entity\LocationEntity';
        $classNames[] = 'MU\ShareModule\Entity\OfferEntity';
        $classNames[] = 'MU\ShareModule\Entity\OfferCategoryEntity';
        $classNames[] = 'MU\ShareModule\Entity\PoolEntity';
        $classNames[] = 'MU\ShareModule\Entity\MessageEntity';
    
        return $classNames;
    }
}
