<?php
/**
 * Share.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\ShareModule\DependencyInjection;

use MU\ShareModule\DependencyInjection\Base\AbstractMUShareExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class MUShareExtension extends AbstractMUShareExtension
{
    // custom enhancements can go here
}
