<?php
/**
 * Share.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\ShareModule\Helper;

use MU\ShareModule\Helper\Base\AbstractNotificationHelper;

/**
 * Notification helper implementation class.
 */
class NotificationHelper extends AbstractNotificationHelper
{
    /**
     * Collects the recipients.
     *
     * @param boolean $debug Whether to add the admin or not
     */
    protected function collectRecipients($debug = false)
    {
        $this->recipients = [];
        
        $recipientId = $this->entity->getRecipient();
        $this->
        $this->addRecipient($this->entity->getRecipient);
    
        if ($debug) {
            // add the admin, too
            $this->addRecipient(UsersConstant::USER_ID_ADMIN);
        }
    }
}
