<?php
/**
 * Share.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\ShareModule\Event;

use MU\ShareModule\Event\Base\AbstractFilterPoolEvent;

/**
 * Event implementation class for filtering pool processing.
 */
class FilterPoolEvent extends AbstractFilterPoolEvent
{
    // feel free to extend the event class here
}
