<?php
/**
 * Share.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\ShareModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\ShareModule\Entity\CompanyEntity;

/**
 * Event base class for filtering company processing.
 */
class AbstractFilterCompanyEvent extends Event
{
    /**
     * @var CompanyEntity Reference to treated entity instance.
     */
    protected $company;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterCompanyEvent constructor.
     *
     * @param CompanyEntity $company Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(CompanyEntity $company, $entityChangeSet = [])
    {
        $this->company = $company;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return CompanyEntity
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * Returns the change set.
     *
     * @return array
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
