<?php
/**
 * Share.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\ShareModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\ShareModule\Entity\PoolEntity;

/**
 * Event base class for filtering pool processing.
 */
class AbstractFilterPoolEvent extends Event
{
    /**
     * @var PoolEntity Reference to treated entity instance.
     */
    protected $pool;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterPoolEvent constructor.
     *
     * @param PoolEntity $pool Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(PoolEntity $pool, $entityChangeSet = [])
    {
        $this->pool = $pool;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return PoolEntity
     */
    public function getPool()
    {
        return $this->pool;
    }

    /**
     * Returns the change set.
     *
     * @return array
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
