services:
    # Entity factory
    mu_share_module.entity_factory:
        class: MU\ShareModule\Entity\Factory\EntityFactory
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@mu_share_module.entity_initialiser"
            - "@mu_share_module.collection_filter_helper"
    
    # Entity initialiser
    mu_share_module.entity_initialiser:
        class: MU\ShareModule\Entity\Factory\EntityInitialiser
        arguments:
        - "@mu_share_module.listentries_helper"
        - "@=service('zikula_extensions_module.api.variable').get('MUShareModule', 'defaultLatitude', 0.00)"
        - "@=service('zikula_extensions_module.api.variable').get('MUShareModule', 'defaultLongitude', 0.00)"
