services:
    # Twig extension
    mu_share_module.twig_extension:
        class: MU\ShareModule\Twig\TwigExtension
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
            - "@mu_share_module.entity_display_helper"
            - "@mu_share_module.workflow_helper"
            - "@mu_share_module.listentries_helper"
        public: false
        tags:
            - { name: twig.extension }
