services:
    # Custom validators
    mu_share_module.validator.list_entry.validator:
        class: MU\ShareModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@mu_share_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: mu_share_module.validator.list_entry.validator }
